name: poly_angular_dart
description: A Dart app that uses Angular 2 and Polymer!
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.18
  browser: ^0.10.0
  polymer: ^1.0.0-rc.17
  polymer_elements: ^1.0.0-rc.8
  web_components: ^0.12.0
  analyzer: 0.27.2
transformers:
- polymer:
    entry_points: web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
